Add IssuingAuthorization, IssuingBalance, IssuingBin, IssuingCard, IssuingHolder, IssuingInvoice, IssuingPurchase, IssuingTransaction, IssuingWithdrawal
starkinfra/sdk-java pull request #3
Opened 2022-04-29 19:12 UTC by xavier-stark

2022-04-29 20:38 UTC, massaru-stark requested changes

2022-04-29 20:38 UTC, massaru-stark commented on CHANGELOG.md
> +- IssuingAuthorization resource
Deixar padronizado com o sdk-python

IssuingAuthorization resource for Sub Issuers
IssuingBalance resource for Sub Issuers
IssuingBin resource for Sub Issuers
IssuingCard resource for Sub Issuers
IssuingHolder resource for Sub Issuers
IssuingInvoice resource for Sub Issuers
IssuingPurchase resource for Sub Issuers
IssuingTransaction resource for Sub Issuers
IssuingWithdrawal resource for Sub Issuers

2022-04-29 20:38 UTC, massaru-stark commented on README.md
> +    - [PixRequests](#create-pixrequests): Create Pix transactions
Dado que você mudou o anchor link aqui, você precisa mudar os headers também pra eles funcionarem
Mesma coisa pros de baixo

2022-04-29 20:38 UTC, massaru-stark commented on README.md
> +    IssuingAuthorization.response(  # this optional method just helps you build the response JSON
Trocar esse # por //

2022-04-29 20:47 UTC, massaru-stark commented on README.md
> +```java
Acho que é melhor deixar esse bloco padronizado com o README do python

2022-04-29 20:47 UTC, massaru-stark commented on README.md
> +
Pode tirar esse enter

2022-04-29 20:47 UTC, massaru-stark commented on README.md
> +        i += 1;
Arrumar a indentação

2022-04-29 20:47 UTC, massaru-stark commented on README.md
> +Generator<IssuingWithdrawal> statements = IssuingWithdrawal.query(params);
Teste de Withdrawal?

2022-04-29 20:47 UTC, massaru-stark commented on README.md
> +System.out.println(i);
Tirar esse print do contador

2022-04-29 20:47 UTC, massaru-stark commented on README.md
> +IssuingTransaction invoices = IssuingTransaction.get("5396424728510464");
invoices -> transaction (no singular)

2022-04-29 20:47 UTC, massaru-stark commented on README.md
> +```java
Usa o padrão da Invoice no bank: https://github.com/starkbank/sdk-java/blob/master/README.md#create-invoices

2022-04-29 20:47 UTC, massaru-stark commented on README.md
> +
Pode tirar essa linha

2022-04-29 20:47 UTC, massaru-stark commented on README.md
> +        System.out.println(request);
Arrumar a indentação

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingBin.java
> +     * limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None.
None -> null

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingBin.java
> +     * limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None.
Inclusive essa descrição ta bem louca kkk

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingBin.java
> +     * @param user [Project object, default null]: Project object. Not necessary if StarkBank.Settings.user was set before function call
Trocar todos os Bank pra Infra

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingBin.java
> +     * limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None.
Linha muito doida

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingBin.java
> +     * @param user [Project object, default null]: Project object. Not necessary if StarkBank.Settings.user was set before function call
Colocar "Organization/Project object" em todos os "user"

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingBin.java
> +     * @return generator of Invoice objects with updated attributes
Invoice -> IssuingBin

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingBin.java
> +     * cursor [string, default None]: cursor returned on the previous page function call
Trocar todos None para null

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +    static ClassData data = new ClassData(IssuingCard.class, "IssuingCard");
Adicionar docstring da classe

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +     * @param display_name [string, default None]: card displayed name. ex: "ANTHONY STARK"
Aqui também está com snake_case

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +     * Parameters:
Precisa dividir o que é required e optional

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +    public IssuingCard(String holderName, String holderTaxId, String holderExternalId, String display_name, String rules[], String bin_id, String[] tags, String street_line_1, String street_line_2, S
Quebrar em várias linhas aqui

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +        this.display_name = (String) dataCopy.remove("display_name");
Aqui também tem o "display_name" e outros em snake_case

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +     * @param user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkinfra.user was set before function call
Está no padrão de python

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +     * @return  list of IssuingCard objects with updated attributes
* Invoice.Page.issuingCards: list of IssuingCards objects with updated attributes
     * Invoice.Page.cursor: cursor to retrieve the next page of IssuingCards objects

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +        /**
Não precisa dessa docstring

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +        /**
Não precisa dessa docstring

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +     * display_name [string, default None]: card displayed name
snake_case

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +    public String[] rules;
Rules precisa ser um Map<>

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +    - after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
Arrumar todas essas datas no padrão de python

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +    - status [string, default None]: filter for status of retrieved objects. ex: "paid" or "registered"
Tá faltando o * no começo das linhas

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +    - status [string, default None]: filter for status of retrieved objects. ex: "paid" or "registered"
Tá faltando o * no começo das linhas

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +
Tirar a linha a mais

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +     * @return  IssuingCard object with updated attributes
Tem um espaço a mais depois do return

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +     * @return  IssuingCard object with updated attributes
Arrumar esse espaço a mais em todos os returns

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +     * Used to define an error in the issuingCard
issuingCard -> IssuingCard

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +            this.reversal = reversal;
reversal -> card

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +        public IssuingCard reversal;
reversal -> card

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +         * @param reversal [IssuingCard]: IssuingCard entity to which the log refers to.
trocar todos os reversal por card

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +         * reversalIds [list of strings, default null]: list of IssuingCard ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
cardIds

2022-04-29 21:32 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingCard.java
> +         * @param params parameters of the query
Arrumar essa linha

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +    static ClassData data = new ClassData(IssuingHolder.class, "IssuingHolder");
Falta docstring da classe

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +    public String[] Rules;
rules tem que ser um Map<> e em camelCase

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +
Tirar esse enter

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +     * @return  IssuingHolder object with updated attributes
espaço a mais

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +     * @return  IssuingHolder object with updated attributes
arrumar nos demais também

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +
Tirar esse enter

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +     * Rules [list of dictionaries, default None]: list of dictionaries with "amount": int, "currencyCode": string, "id": string, "interval": string, "name": string pairs
Arrumar essa linha

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +    public final static class Error extends SubResource {
Tirar esse Error, não é pra existir

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +        public IssuingHolder reversal;
reversal -> holder

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +        public IssuingHolder reversal;
Arrumar no código e docstrings

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +         * reversalIds [list of strings, default null]: list of IssuingHolder ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
holderIds

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +         * reversalIds [list of strings, default null]: list of IssuingHolder ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
holderIds
Arrumar em todos os outros lugares

2022-04-29 21:48 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingHolder.java
> +
Tirar essa linha

2022-04-29 22:02 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingTransaction.java
> +     * ids [list of strings, default [], default None]: purchase IDs
Dois defaults

2022-04-29 22:02 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingTransaction.java
> +     * external_ids [list of strings, default []]: external IDs. ex: ["5656565656565656", "4545454545454545"]
arrumar nos outros lugares também

2022-04-29 22:02 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingTransaction.java
> +
Tirar essa linha

2022-04-29 22:12 UTC, cdottori-stark commented on src/test/java/TestBalance.java
> +        IssuingBalance balance = IssuingBalance.get();
wut

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +    static ClassData data = new ClassData(IssuingInvoice.class, "IssuingInvoice");
docstring da Class

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +
Tirar linha em branco

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +     * @return generator of IssuingInvoices objects with updated attributes
generator -> list

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +     * @return generator of IssuingInvoices objects with updated attributes
Adicionar o cursor no return

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +     * @return generator of IssuingInvoices objects with updated attributes
Em todos os outros page() também

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +    public final static class Error extends SubResource {
Remover esse Error, não precisa existir

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +        public List<IssuingInvoice.Error> errors;
Esse erros não existe, pode tirar

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +        public List<IssuingInvoice.Error> errors;
Tirar dos métodos e afins

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +        public IssuingInvoice reversal;
reversal -> invoice

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +         * reversalIds [list of strings, default null]: list of IssuingInvoice ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
invoiceIds

2022-04-29 22:14 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingInvoice.java
> +         * Use this function instead of query if you want to manually page your reversals.
Não é reversals

2022-04-29 22:16 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingBalance.java
> +    static ClassData data = new ClassData(IssuingBalance.class, "IssuingBalance");
falta a docstring da classe

2022-04-29 22:16 UTC, massaru-stark commented on src/main/java/com/starkinfra/IssuingBin.java
> +    static ClassData data = new ClassData(IssuingBin.class, "IssuingBin");
Falta a docstring da classe

2022-04-29 22:17 UTC, cdottori-stark commented on src/test/java/TestIssuingInvoice.java
> +        Generator<IssuingInvoice> statements = IssuingInvoice.query(params);
invoice?

2022-04-29 22:18 UTC, cdottori-stark commented on src/test/java/TestIssuingInvoice.java
> +        Generator<IssuingHolder.Log> logs = IssuingHolder.Log.query(params);
holder?

2022-04-29 22:18 UTC, cdottori-stark commented on src/test/java/TestIssuingPurchase.java
> +
espaço

2022-04-29 22:18 UTC, cdottori-stark commented on src/test/java/TestIssuingPurchase.java
> +
espaço

2022-05-02 01:38 UTC, cdottori-stark approved these changes

2022-05-02 01:38 UTC, merged